### ISSUE TITLE
Flickering Engineer's Report and Contracts in VAB

### ISSUE THREAD

**Issue by RealKolago** [BobPalmer/CommunityResourcePack#121]
Something strange goes on in my game...

I started a career game with some mods installed and at some point the Engineer's Report and Contracts as well as the App Launcher buttons getting flickering and unreadable in the VAB.

This was not right away but after doing some contracts.

So I deinstalled all mods and at the end there was only CommunityResourcePack (0.6.0.0) left.
After all I pinned it down to one file: CommonResources.cfg

Screenshots:
http://imgur.com/JCN8Fql
http://imgur.com/OmivqJV

output_log.txt
https://mega.nz/#!Ot8DWCoS!SRt2k-AaILPv0N7xxKoGycd6MoaipAn5Zcv_ibnski4

**Comment by sswelm** [comment]
I don't think it has anythng to do with CRP, which is just a bunch or definitions

**Comment by RealKolago** [comment]
So why is the problem gone when I remove CDR? I know that most of the time its some mod with DLL that buggy. But I removed all of them. Looks like there is something with career game, contracts and resources (CDR). How can this influence the GUI? Maybe a bug in KSP itself.

**Comment by sswelm** [comment]
More likely the lack of CRP causes some other subsystem not to function at all which was causing the flickering problem

**Comment by Ferigad** [comment]
Just to let you know, i got the same issue. And tryed several ways, like complete reinstallation, reboot, one by one mod adding, nothing solves it. And i can´t pinpoint it. One time it showed up when i added DScience Mod, the next time when i added K+, the next time when i added Deepfreeze. I am not sure if it has something to do with the CRP but still something odd goes on.

**Comment by RealKolago** [comment]
All point to KSP itself with to many parts added.

**Comment by sswelm** [comment]
flickering problems are resolved in KSP 1.2.1. This can be closed
