### ISSUE TITLE
Double definition of LqdFluorine

### ISSUE THREAD

**Issue by PhineasFreak** [BobPalmer/CommunityResourcePack#133]
The resource "LqdFluorine" is defined twice, one time at the lines [764 - 776](https://github.com/BobPalmer/CommunityResourcePack/blob/master/FOR_RELEASE/GameData/CommunityResourcePack/CommonResources.cfg#L764-L776) (KSPI-E) and another time at the lines [1516 - 1526](https://github.com/BobPalmer/CommunityResourcePack/blob/master/FOR_RELEASE/GameData/CommunityResourcePack/CommonResources.cfg#L1516-L1526) (RealFuels).
- KSP version: 1.2.0.1586
- CRP version: 0.6.2.0

**Comment by sswelm** [comment]
Indeed, we have to do something about

**Comment by sswelm** [comment]
I think it can be closed now

**Comment by PhineasFreak** [comment]
Yep, thanks for that!
