### ISSUE TITLE
Change BioMass resource

### ISSUE THREAD

**Issue by Olympic1** [BobPalmer/CommunityResourcePack#15]
Just a reminder for changing the BioMass Resource

```
RESOURCE_DEFINITION
{
    name = BioMass
    density = 0.003825
    flowMode = STACK_PRIORITY_SEARCH
    transfer = PUMP
    isTweakable = true
    unitCost = 3.825
}
```

http://forum.kerbalspaceprogram.com/threads/53009?p=1649605&viewfull=1#post1649605
and
http://forum.kerbalspaceprogram.com/threads/53009?p=1650047&viewfull=1#post1650047

**Comment by BobPalmer** [comment]
Updating this in the next CRP release

**Comment by BobPalmer** [comment]
Actually... since we're switching to stuff in 1.0 anyway - deprecating this as the biomass team is a bit unresponsive and I don't want to stomp over their things.
