### ISSUE TITLE
please change density of rock (should be 10x as dense)

### ISSUE THREAD

**Issue by riocrokite** [BobPalmer/CommunityResourcePack#19]
IMHO it should be 
0.0025 instead of 0.00025

It should be 2.5 heavier than water per m3 and now it is 4 times lighter :(
(water density is 0.001)

source - common rock densities compared to water:
http://geology.about.com/cs/rock_types/a/aarockspecgrav.htm

**Comment by BobPalmer** [comment]
Countersource:  The density of asteroids when compared with volume (for whatever reason, Squad made asteroids very 'fluffy'.  Changing this would cause massive conservation of mass issues.
