### ISSUE TITLE
The typing error still in there

### ISSUE THREAD

**Issue by Gordon-Dry** [BobPalmer/CommunityResourcePack#190]
A couple of weeks ago in the forum someone mentioned that error and how to fix it.
But until now it's still in there, incl. all versions packaged with other mods.

GameData\CommunityResourcePack\CommonResources.cfg:
Line 602:
	dispalyName = #LOC_CRP_EnrichedUranium_DisplayName // Nuclear fuel

Change dispalyName to displayName

**Comment by theRagingIrishman** [comment]
fixed in next release @BobPalmer please close
