### ISSUE TITLE
Duna Poles Water

### ISSUE THREAD

**Issue by NihilRex** [BobPalmer/CommunityResourcePack#20]
Current Config has polar water as Atmospheric, type 2, instead of Crustal, type 0

REGOLITH_BIOME_RESOURCE
{
	ResourceName = Water
	ResourceType = 2
	PlanetName = Duna
	BiomeName = Poles
	
	Distribution
	{
		PresenceChance = 100
		MinAbundance = 5
		MaxAbundance = 20
		Variance = 10
	}
}

Should be 

REGOLITH_BIOME_RESOURCE
{
	ResourceName = Water
	ResourceType = **0**
	PlanetName = Duna
	BiomeName = Poles
	
	Distribution
	{
		PresenceChance = 100
		MinAbundance = 5
		MaxAbundance = 20
		Variance = 10
	}
}

**Comment by BobPalmer** [comment]
Fixed :)
