### ISSUE TITLE
Plutonium-238

### ISSUE THREAD

**Issue by Bear67** [BobPalmer/CommunityResourcePack#26]
Not really an Issue, just a FYI info on what it is.
http://en.wikipedia.org/wiki/Plutonium-238
If I'm understanding the wiki right, it could be produced during the reprocess of spent Nuclear Fuel, in KSP you could have a bit generated when reprocessing DepletedUranium back into EnrichedUranium.

**Comment by BobPalmer** [comment]
Added as part of MKS
