### ISSUE TITLE
Regolith resource definitions should be moved from CRP to actual mods that use them (REGOLITH_BIOME_RESOURCE, REGOLITH_PLANETARY_RESOURCE,REGOLITH_GLOBAL_RESOURCE)

### ISSUE THREAD

**Issue by riocrokite** [BobPalmer/CommunityResourcePack#27]
A question/suggestion regarding Regolith and CRP to avoid mod conflicts.

As I understand Regolith along with CRP should be a flexible base for mods to play nicely and avoid conflicts with composition:

"So first and foremost on the list is how to deal cleanly with multiple mods who may have very different ideas on composition. etc. (i.e. is Jool a ball of Karbonite or a ball of Hydrogen?)"

However CRP adds ResourceConfigs folder which should IMHO be included in actual mod that defines it, not CRP itself. So karbonite resource config IMHO should be in Karbonite mod, not CRP. 

For example I'm creating a fantasy mod in which there should be 1% chance for water on Kerbin. I'm creating regolith-based config for water on kerbin (1% chance). I want my mod to play nicely with i.e. NearFuture stuff so add I dependency for CRP and Regolith.

However CRP itself in ResourceConfigs folder holds definition of Water for Kerbin with presence chance of 100%. So my config of 1% is overriden by CRP's one since it is more optimistic (100%). The only way I can force 1% chance is to modify actual CRP config via MM which is regarded as not nice.

All in all I feel that in current form CRP/Regolith dictates composition for certain resources. Thus my suggestion of moving ResourceConfigs from CRP to actual mods that use them.

**Comment by BobPalmer** [comment]
Closing as part of CRP is also resource harvesting.
