### ISSUE TITLE
Update CRP.version to reflect KSP 1.0

### ISSUE THREAD

**Issue by somnambulistic** [BobPalmer/CommunityResourcePack#32]
CRP.version still lists KSP_VERSION and KSP_VERSION_MAX as .90

**Comment by sshadowwraith** [comment]
Agreed. Also, the version of CRP in the .version file is still listed as :
     "VERSION":{
     "MAJOR":0,
     "MINOR":3,
     "PATCH":3,
     "BUILD":0
     },

**Comment by 602p** [comment]
I've submitted a PR to address this ( #36 )
