### ISSUE TITLE
Parts not after reverting flight to VAB/SPH

### ISSUE THREAD

**Issue by lterys** [BobPalmer/CommunityResourcePack#42]
Tested in diferent computers in stock / unmoded game, game version 1.0.2, and only CRP and Squad's folders.

It seems that somehow the config files are causing problems loading parts after "Revert to VAB" is done, like the game not being able to find a determinate resource?

Deleting the configs seems to stop the bug from occur after is triggered (and its done after firstly discovered / scanned Kerbin's resources). 

To reproduce it, create a new savegame and discover Kerbin's resources, then launch a vehicle and revert back to VAB/SPH, it can take several tries to reproduce it, relaunch and revert and eventually the VAB will load without parts available.

The error might be related with this line under ResourceScenario in the persistent savegame:

				PlanetId = 1

(Deleting it stops the bug from occur).

The most modded the installation, the most frequent it seems to be the occurrence.

Sorry I can't be more helpful I lack of the proper knowledge and I can only narrow it this far...

**Comment by Joshwoo69** [comment]
agreed
