### ISSUE TITLE
Request: Oxygen around Kerbol

### ISSUE THREAD

**Issue by ArnePeirs** [BobPalmer/CommunityResourcePack#57]
In KSP 1.0 they gave Kerbol an atmosphere (600000m) that contains oxygen. Maybe add a config to add a low concentration of oxygen to Kerbol's atmosphere.

**Comment by sswelm** [comment]
Not sure if that makes any sense from a game-play or a realism point of view.  The sun only contains small amount of oxygen, which it's heavier than hydrogen, meaning it will not be very abundant in the atmosphere. It's much more likely you might find Hydrogen and Helium in the suns atmosphere. From a game play point o view it would not be worth much as getting here requires an insane amount of delta V meaning Oxygen is almost useless. Also being at this low orbit, would give extreme amount of ultra violet radiation..
