### ISSUE TITLE
Support for Real Solar System?

### ISSUE THREAD

**Issue by pjf** [BobPalmer/CommunityResourcePack#6]
This is *very* much a wishlist item, but I'm popping it here in any case anyone's working on it. I would *love* to see a Real Solar System version of the CRP. Ice deposits in polar craters on the moon, Karbonite deposits on Europa... it would be grand. :)

I've noticed some of the resource maps are based upon terrain height. I don't know if there are existing tools to do map generation, but I've got a good chance of being able to get height maps of various sorts off the RSS folks.

Many thanks for all your great work!

~ Paul

**Comment by BobPalmer** [comment]
Just catching this up a bit.  No PNGs needed, all you need to do to enable mining support is just add in some Regolith configs (ping me if you need help).  Closing for now as there are no CRP action items right now.
