### ISSUE TITLE
Missing water

### ISSUE THREAD

**Issue by DragonEater** [BobPalmer/CommunityResourcePack#81]
So after much looking around in files and configs, I found a way to fix the problem but it is not good practice.

PROBLEM:
There is no water on the Muun, the scanner comes back at 0.0% in all biomes. ( M-700 shows as 0.0 Average as well )

SOLUTION:
In "persistent.sfs" I changed my "GameSeed" Number by one digit, now I have water but all other resources moved around, that part was expected.

If I change the GameSeed number back to the original one, the water goes away again.

Can a 'bad' seed cause the removal of an entire resource? Is tehre a way to confirm all other planets / moons are OK before I set up shop and find that Duna has no Minerals?

**Comment by sswelm** [comment]
There is not supposed to be water on the moon for most oft the lunar surface except a low concentration in a few large craters at the poles, just like in reality on our own moon

**Comment by BobPalmer** [comment]
Actually, Mun != Moon.  That being said, for all biomes/bodies (except where specifically allowed or overridden), water distribution is relatively rare, and random per biome so sounds like the OP got bad luck with the RNG.  Unrelated, mun_water.png is irrelevant for CRP - it uses stock resources, not image-based distributions.

So there is nothing wrong with your seed, an occassional lack of resources is totally expected and normal, based on the default settings in the CRP resources folder.

Closing this as not an issue.

**Comment by DragonEater** [comment]
Thanks for the answer and awesome info!
