### ISSUE TITLE
The unitCost of Supplies is substantially too high

### ISSUE THREAD

**Issue by fraz86** [BobPalmer/CommunityResourcePack#85]
At the current unitCost of 15, Supplies often represent 25-50% of the total cost of a manned interplanetary mission (with USI-LS). In reality, the cost of the food, water, and oxygen is trivial. It's the cost of lifting these supplies into space that makes them precious commodities.

For another line of reasoning, consider that 1 Kerbal Fund is roughly equivalent to 1000 USD (just a ballpark figure - by this conversion, some stock parts are overpriced and many are underpriced). Thus, 1 liter of Supplies (i.e., mostly water, plus a little bit of food and oxygen) currently costs around 15,000 USD, which is multiple orders of magnitude too high. Even 50 USD per liter seems expensive, which translates to a unitCost of 0.05.

If the cost of Supplies is lowered, the cost of Mulch should also be decreased. Perhaps it would be most sensible to set Mulch's cost to zero, since I doubt there's any real value in recovering kerbonauts' waste water, feces, and carbon dioxide.

**Comment by BobPalmer** [comment]
Changed in next release
